export const GET_MAX_CREDITS = 'GET_MAX_CREDITS';
export const SET_MAX_CREDITS = 'SET_MAX_CREDITS';
export const GET_MAX_CREDITS_ERROR = 'GET_MAX_CREDITS_ERROR';
export const BET_REQUEST = 'BET_REQUEST';
export const BET_SUCCESS = 'BET_SUCCESS';
export const BET_ERROR = 'BET_ERROR';
export const STOP_BET_SUCCESS = 'STOP_BET_SUCCESS';
export const STOP_BET_ERROR = 'STOP_BET_ERROR';
export const END_BET = 'END_BET';
export const SET_AUTO_BET = 'SET_AUTO_BET';
export const STOP_AUTO_BET = 'STOP_AUTO_BET';

export const SET_PUBLICKEY = 'SET_PUBLICKEY';
export const GET_PRIZE = 'GET_PRIZE';

export const SET_FINGER_PRINTER = 'SET_FINGER_PRINTER';
export const SET_DISPLAY_VALUE = 'SET_DISPLAY_VALUE';


export const GET_TRANSACTION_HISTORY_SUCCESS = 'GET_TRANSACTION_HISTORY_SUCCESS';
export const GET_TRANSACTION_HISTORY_ERROR = 'GET_TRANSACTION_HISTORY_ERROR';

export const GET_MY_RECENT_WINS_SUCCESS = 'GET_MY_RECENT_WINS_SUCCESS';
export const GET_MY_RECENT_WINS_ERROR = 'GET_MY_RECENT_WINS_ERROR';

export const GET_GAME_COINS = 'GET_GAME_COINS';

export const GET_ALL_BET_SUCCESS = 'GET_ALL_BET_SUCCESS';
export const GET_ALL_BET_ERROR = 'GET_ALL_BET_ERROR';

export const GET_GAME_HISTORY_SUCCESS = 'GET_GAME_HISTORY_SUCCESS';
export const GET_GAME_HISTORY_ERROR = 'GET_GAME_HISTORY_ERROR';

export const GET_LEADERBOARD_SUCCESS = 'GET_LEADERBOARD_SUCCESS';
export const GET_LEADERBOARD_ERROR = 'GET_LEADERBOARD_ERROR';

export const GET_LOGIN_REQUEST_REQUEST = 'GET_LOGIN_REQUEST_REQUEST';
export const GET_LOGIN_REQUEST_SUCCESS = 'GET_LOGIN_REQUEST_SUCCESS';
export const GET_LOGIN_REQUEST_ERROR = 'GET_LOGIN_REQUEST_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const GET_REGISTERED_STATUS_REQUEST = 'GET_REGISTERED_STATUS_REQUEST';
export const GET_REGISTERED_STATUS_SUCCESS = 'GET_REGISTERED_STATUS_SUCCESS';
export const GET_REGISTERED_STATUS_ERROR = 'GET_REGISTERED_STATUS_ERROR';

export const GET_STATS_REQUEST = 'GET_STATS_REQUEST';
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS';
export const GET_STATS_ERROR = 'GET_STATS_ERROR';

export const GET_USER_STATS_REQUEST = 'GET_USER_STATS_REQUEST';
export const GET_USER_STATS_SUCCESS = 'GET_USER_STATS_SUCCESS';
export const GET_USER_STATS_ERROR = 'GET_USER_STATS_ERROR';

export const GET_USERNAME_REQUEST = 'GET_USERNAME_REQUEST';
export const GET_USERNAME_SUCCESS = 'GET_USERNAME_SUCCESS';
export const GET_USERNAME_ERROR = 'GET_USERNAME_ERROR';

export const GET_PUBLICKEY_SUCCESS = 'GET_PUBLICKEY_SUCCESS';

export const GET_ONLINE_PLEYERS_SUCCESS = 'GET_ONLINE_PLEYERS_SUCCESS';
export const GET_ONLINE_PLEYERS_ERROR = 'GET_ONLINE_PLEYERS_ERROR';

export const DEPOSIT_REQUEST = 'DEPOSIT_REQUEST';

export const SET_GAME_RESULT = 'SET_GAME_RESULT';

export const SET_POPUP = 'SET_POPUP';

export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';

export const CHANGE_GAME_STATE = 'CHANGE_GAME_STATE';

export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';

export const SHOW_BANKROLL_MODAL = 'SHOW_BANKROLL_MODAL';
export const HIDE_BANKROLL_MODAL = 'HIDE_BANKROLL_MODAL';
export const SHOW_WITHDRAW_MODAL = 'SHOW_WITHDRAW_MODAL';
export const HIDE_WITHDRAW_MODAL = 'HIDE_WITHDRAW_MODAL';
export const SHOW_SELECT_NETWORK_MODAL = 'SHOW_SELECT_NETWORK_MODAL';
export const HIDE_SELECT_NETWORK_MODAL = 'HIDE_SELECT_NETWORK_MODAL';
export const SHOW_DEPOSIT_MODAL = 'SHOW_DEPOSIT_MODAL';
export const HIDE_DEPOSIT_MODAL = 'HIDE_DEPOSIT_MODAL';
export const SHOW_DAILY_BONUS_MODAL = 'SHOW_DAILY_BONUS_MODAL';
export const HIDE_DAILY_BONUS_MODAL = 'HIDE_DAILY_BONUS_MODAL';
export const SHOW_SELECT_WALLET_MODAL = 'SHOW_SELECT_WALLET_MODAL';
export const HIDE_SELECT_WALLET_MODAL = 'HIDE_SELECT_WALLET_MODAL';
export const SHOW_WHEEL_PRIZE_SPIN_MODAL = 'SHOW_WHEEL_PRIZE_SPIN_MODAL';
export const HIDE_WHEEL_PRIZE_SPIN_MODAL = 'HIDE_WHEEL_PRIZE_SPIN_MODAL';
export const SHOW_WHEEL_PRIZE_WIN_MODAL = 'SHOW_WHEEL_PRIZE_WIN_MODAL';
export const HIDE_WHEEL_PRIZE_WIN_MODAL = 'HIDE_WHEEL_PRIZE_WIN_MODAL';

export const SHOW_STATS_MODAL = 'SHOW_STATS_MODAL';
export const HIDE_STATS_MODAL = 'HIDE_STATS_MODAL';

export const HIDE_HELP_MODAL = 'HIDE_HELP_MODAL';
export const SHOW_HELP_MODAL = 'SHOW_HELP_MODAL';

export const HIDE_HELP_DETAIL_MODAL = 'HIDE_HELP_DETAIL_MODAL';
export const SHOW_HELP_DETAIL_MODAL = 'SHOW_HELP_DETAIL_MODAL';

export const HIDE_LEADERBOARD_MODAL = 'HIDE_LEADERBOARD_MODAL';
export const SHOW_LEADERBOARD_MODAL = 'SHOW_LEADERBOARD_MODAL';

export const HIDE_TX_SIGN_MODAL = 'HIDE_TX_SIGN_MODAL';
export const SHOW_TX_SIGN_MODAL = 'SHOW_TX_SIGN_MODAL';

export const HIDE_HISTORY_MODAL = 'HIDE_HISTORY_MODAL';
export const SHOW_HISTORY_MODAL = 'SHOW_HISTORY_MODAL';

export const HIDE_FORGOT_PASSWORD_MODAL = 'HIDE_FORGOT_PASSWORD_MODAL';
export const SHOW_FORGOT_PASSWORD_MODAL = 'SHOW_FORGOT_PASSWORD_MODAL';

export const SHOW_RESET_PASSWORD_MODAL = 'SHOW_RESET_PASSWORD_MODAL';
export const HIDE_RESET_PASSWORD_MODAL = 'HIDE_RESET_PASSWORD_MODAL';

export const SET_BACK_AUDIO_VOLUME = 'SET_BACK_AUDIO_VOLUME';
export const SET_EFFECT_AUDIO_VOLUME = 'SET_EFFECT_AUDIO_VOLUME';
export const SET_MUTE_AUDIO = 'SET_MUTE_AUDIO';
export const SET_BET_BUTTON_VOLUME = 'SET_BET_BUTTON_VOLUME';

export const SET_TIME_TO_START = 'SET_TIME_TO_START';

export const SET_ROUND_WIN = 'SET_ROUND_WIN';

export const GET_LAST_RESULTS = 'GET_LAST_RESULTS';

export const GET_MAX_PROFIT = 'GET_MAX_PROFIT';

export const BOOK_BET = 'BOOK_BET';

export const STOP_BOOK_BET = 'STOP_BOOK_BET';

export const SET_LATEST_RESULTS = 'SET_LATEST_RESULTS';
    
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';

export const CHANGE_CURRENT_BET_COION = 'CHANGE_CURRENT_BET_COION';

export const PLAY_BETBUTTON_CLICK_SOUND = 'PLAY_BETBUTTON_CLICK_SOUND';
export const PLAY_CLOSEBUTTON_CLICK_SOUND = 'PLAY_CLOSEBUTTON_CLICK_SOUND';
export const PLAY_BET_SOUND = 'PLAY_BET_SOUND';
export const PLAY_SPIN_BTN_CLICK_SOUND = 'PLAY_SPIN_BTN_CLICK_SOUND';

export const SET_PASSWORD_RESET_DATA = 'SET_PASSWORD_RESET_DATA';

export const CHANGE_USE_CHAIN_ID = 'CHANGE_USE_CHAIN_ID';

export const CHANGE_CURRENT_CHAIN_ID = 'CHANGE_CURRENT_CHAIN_ID';

export const SET_SIGNED = 'SET_SIGNED';

export const TRANSACTION_TYPE = {
    WITHDRAW: 'Withdraw',
    DEPOSIT: 'Deposit',
    REWARD: 'Reward',
    EVENT: 'Event',
    NONE: ''
}

export const GAME_HISTORY_TYPE = {
    ALL: 'All',
    HIGH_WINS: 'High Wins',
    LUCKY_WINS: 'Lucky Wins',
    MY_WAGER: 'My Wager',
    NONE: ''
}

export const GAME_STATE = {
    WAITING: 'WAITING',
    RUNNING: 'RUNNING',
    CRASHED: 'CRASHED',
    NONE: 'NONE'
}

export const BET_COIN = {
    BNB: 'BNB',
    BITS: 'Bits',
    NONE: 'NONE'
}

export const betAmountMultiple = {
    half: 'half',
    double: 'double',
    max: 'max',
    min: 'min'
};

export const MY_STATS_CHART_TYPE = {
    GAME_PLAYED: 'GAME_PLAYED',
    TOTAL_WAGERED: 'TOTAL_WAGERED',
    NET_PROFIT: 'NET_PROFIT'
};

export const SOUND_TYPE = {
    PLAY: 'PLAY',
    STOP_ON_PLAYING: 'STOP_ON_PLAYING',
    CANCEL: 'CANCEL'
};